### ISSUE TITLE
A problem with the markdown parser

### ISSUE THREAD

**Issue by coolreader18** [PaulKlinger/Sprog-Backend#1]
I'm pretty sure that this is the right repository.

The markdown parser being used for this is different than Reddit, it recognizes _underscores_ (`_underscores_`) as italics. This is mostly recognizable when somebody says something like, "Thanks to u/Poem\_for\_your\_sprog" but it shows up as "Thanks to u/Poem*for*your_sprog". I don't know if what you use is configurable, but if it is, you should turn off underline italics.r

**Comment by PaulKlinger** [comment]
The markdown is converted separately in the Android app, so https://github.com/PaulKlinger/Sprog-App would be the right repository, but no worries.

It seems like reddit does use underscore for italics, but only if there is no non-whitespace character after the second underscore. The library I use doesn't have an option for that but I fixed it with a bit of a hack. 

I've released a new version of the app, it should be available in a few hours.

Thanks for noticing and reporting this!
