### ISSUE TITLE
Markdown To Latex

### ISSUE THREAD

**Issue by TomGranot** [PaulKlinger/Sprog-Backend#2]
Hey! 

Great app - I've been getting my daily Sprog dose through it for the past few months.
A quick question - what's with the conversion from Markdown To LateX?
Are all the poems displayed as LateX?

Cheers,

Tom

**Comment by PaulKlinger** [comment]
Hi!

The LaTeX is used to generate the pdfs on https://almoturg.com/sprog/, not
for the app. The app directly uses the reddit markdown.

Thanks for using the app!
All the Best,
Paul

**Comment by TomGranot** [comment]
OK great, thanks!
